
const Data = [

        {
                name: "Ibrohim Akromov",
                address: "Toshkent shahar Yashnobod tumani Ohangrabo-54 ",
                tel: +998946910781,
                state: "AQSH",
                direction: "Garvard universiteti",
                payment: "1-sentabr 3 000 000",
                payment2: "15-sentabr 3 000 000",
                manager: "Mushtariy",
                status: "active",
                statusRealTime: 'tolagan',
                id: "1",
                passport: "passport1.jpg",
                image: "de2.png",
                actives: "tolagan",
                ustoz: "Sherzod",
        },
        {
                name: "Izzat Toychiyev",
                address: "Toshkent shahar Yashnobod tumani Tosh kochasi-78 ",
                tel: +998978888778,
                state: "Qozogiston",
                direction: "Almata universiteti Rus tili",
                payment: "1-sentabr 3 000 000",
                payment2: "15-sentabr 3 000 000",
                manager: "Madina",
                status: "Checked",
                statusRealTime: 'tolagan',
                id: "2",
                passport: "passport1.jpg",
                image: "de2.png",
                actives: "tolagan",
                ustoz: "Sherzod",

        },
        {
                name: "Asad fbjfj",
                address: "Qashqadaryo viloyati Qamashi tumani Terak-90 ",
                tel: +998997777700,
                state: "Qirgiziston",
                direction: "Osh davlat universiteti Ingliz tili",
                payment: "1-sentabr 3 000 000",
                payment2: "15-sentabr 3 000 000",
                manager: "Komila",
                status: "Not active",
                statusRealTime: 'tolamagan',
                id: "3",
                passport: "passport1.jpg",
                image: "de2.png",
                actives: "tolamagan",
                ustoz: "Alisher",

        },
        {
                name: "Doniyor Deff",
                address: "Samarqand viloyati Registon-554 ",
                tel: +99890999999,
                state: "Qirgiziston",
                direction: "Osh davlat universiteti Ingliz tili",
                payment: "1-sentabr 3 000 000",
                payment2: "15-sentabr 3 000 000",
                manager: "Omina",
                status: "Checked",
                statusRealTime: 'tolamagan',
                id: "4",
                passport: "passport1.jpg",
                image: "de2.png",
                actives: "tolamagan",
                ustoz: "Sherzod",

        },
        {
                name: "Anvar Toychidfyev",
                address: "Andijon viloyati Asaka-97 ",
                tel: +998998576423,
                state: "Qirgiziston",
                direction: "Osh davlat universiteti Ingliz tili",
                payment: "1-sentabr 3 000 000",
                payment2: "15-sentabr 3 000 000",
                manager: "Salima",
                status: "active",
                statusRealTime: 'tolagan',
                id: "5",
                passport: "passport1.jpg",
                image: "de2.png",
                actives: "tolagan",
                ustoz: "Xusan",

        },
        {
                name: "Kamol fsf",
                address: "Surxondaryo viloyti chegara-11 ",
                tel: +998941122211,
                state: "Qirgiziston",
                direction: "Osh davlat universiteti Ingliz tili",
                payment: "1-sentabr 3 000 000",
                payment2: "15-sentabr 3 000 000",
                manager: "Salima",
                status: "active",
                id: "6",
                passport: "passport1.jpg",
                image: "de2.png",
                actives: "tolamagan",
                ustoz: "Sherzod",

        }

]

export default Data